"""Human-readable French labels for the fine crop codes in CULT_2017.set.

Ported from context/gams/DESCRIPTION_SETS.txt (GAMS source of
truth). Figures and exports use these instead of raw codes. The 24 MA_<mulch>_*
maraichage subtypes are not individually described in the GAMS source: mulch
(BAG=bagasse/BRF/PAI=paille) and irrigation (I/NI) are decoded; the middle
fertilisation token (BIO/VEG/FER/NON) is kept literal (meaning undocumented --
see docs/04-vigilance.md). label_for() falls back to the raw code for anything unmapped.
"""

CROP_LABELS: dict[str, str] = {
    'AG': 'Agrumes',
    'AN': 'Ananas',
    'AN_NU': 'Ananas: systèmes technique sans paillage plastique',
    'AN_PA': 'Ananas: systèmes technique avec paillage plastique',
    'BA': 'Banane fruit',
    'BA_INT': 'Banane: système technique intensif en plaine',
    'BA_IRR': 'Banane: système technique irrigué',
    'BA_PER': 'Banane: système technique extensif en montange',
    'BA_SINT': 'Banane: système technique intensif en montagne',
    'BC': 'Banane plantain',
    'BC_BT': 'Banane plantain Basse-Terre',
    'BC_GTMG': 'Banane plantain Grande-Terre & Marie-Galante',
    'CF_NBT_NISM': 'Canne fibre: Nord Basse-Terre, non irrigué, récolte semi-mécanisée',
    'CF_NBT_NIM': 'Canne fibre: Nord Basse-Terre, non irrigué, récolte mécanisée',
    'CF_SBT_NISM': 'Canne fibre: Sud Basse-Terre, non irrigué, récolte semi-mécanisée',
    'CF_SBT_NIM': 'Canne fibre: Nord Basse-Terre, non irrigué, récolte mécanisée',
    'CF_NGT_NISM': 'Canne fibre: Nord Grande-Terre, non irrigué, récolte semi-mécanisée',
    'CF_NGT_NIM': 'Canne fibre: Nord Grande-Terre, non irrigué, récolte mécanisée',
    'CF_CGT_NISM': 'Canne fibre: Centre Grande-Terre, non irrigué, récolte semi-mécanisée',
    'CF_CGT_NIM': 'Canne fibre: Centre Grande-Terre, non irrigué, récolte mécanisée',
    'CF_EGT_NISM': 'Canne fibre: Est Grande-Terre, non irrigué, récolte semi-mécanisée',
    'CF_EGT_NIM': 'Canne fibre: Est Grande-Terre, non irrigué, récolte mécanisée',
    'CS': 'Canne à sucre',
    'CS_BT_NISM': 'Canne à sucre: Basse-Terre, non irrigué, récolte semi-mécanisée',
    'CS_BT_NIM': 'Canne à sucre: Basse-Terre, non irrigué, récolte mécanisée',
    'CS_BT_IM': 'Canne à sucre: Basse-Terre, irrigué, récolte mécanisée',
    'CS_SBT_NISM': 'Canne à sucre: Sud-Est Basse-Terre, non irrigué, récolte semi-mécanisée',
    'CS_SBT_NIM': 'Canne à sucre: Sud-Est Basse-Terre, non irrigué, récolte mécanisée',
    'CS_SBT_IM': 'Canne à sucre: Sud-Est Basse-Terre, irrigué, récolte mécanisée',
    'CS_NGT_NISM': 'Canne à sucre: Nord Grande-Terre, non irrigué, récolte semi-mécanisée',
    'CS_NGT_NIM': 'Canne à sucre: Nord Grande-Terre, non irrigué, récolte mécanisée',
    'CS_NGT_IM': 'Canne à sucre: Nord Grande-Terre, irrigué, récolte mécanisée',
    'CS_CGT_NISM': 'Canne à sucre: Centre Grande-Terre, non irrigué, récolte semi-mécanisée',
    'CS_CGT_NIM': 'Canne à sucre: Centre Grande-Terre, non irrigué, récolte mécanisée',
    'CS_CGT_IM': 'Canne à sucre: Centre Grande-Terre, irrigué, récolte mécanisée',
    'CS_EGT_NISM': 'Canne à sucre: Est Grande-Terre, non irrigué, récolte semi-mécanisée',
    'CS_EGT_NIM': 'Canne à sucre: Est Grande-Terre, non irrigué, récolte mécanisée',
    'CS_EGT_IM': 'Canne à sucre: Est Grande-Terre, irrigué, récolte mécanisée',
    'CS_MG_NISM': 'Canne à sucre: Marie-Galante, non irrigué, récolte semi-mécanisée',
    'CS_MG_NIM': 'Canne à sucre: Marie-Galante, non irrigué, récolte mécanisée',
    'CS_MG_IM': 'Canne à sucre: Marie-Galante, irrigué, récolte mécanisée',
    'IG': 'Igname et tubercules tropicaux',
    'IG_PLA': 'Igname à plat',
    'IG_TUT': 'Igname tuteuré',
    'JA': 'Jachère',
    'MA': 'Maraîchage de plein champs hors tubercules tropicaux',
    'MA_TO_CHOU_JA': 'Maraîchage plein champ (rotation TO/CHOU/JA)',
    'MA_PLBIO': 'Maraichage biologique plurispécifique',
    'MA_MOBIO': 'Maraichage biologique monospécifique',
    'MA_ROTA': 'Maraichage en rotation',
    'ME': 'Melon',
    'NC': 'Non cultivé',
    'PN': 'Prairies & savanes',
    'PN_PIQ': 'Prairies naturelles avec elevage au piquet',
    'PN_TOUR': 'Prairies naturelles avec paturage tournant',
    'TH': 'Tomate',
    'VE': 'Vergers hors agrumes',
    'VE_BTGT': 'Vergers: Basse-Terre & Grande-Terre',
    'VE_PLUIE': 'Vergers: Zones très pluvieuses',
    'MA_TO_CO_JA': 'Maraîchage plein champ (rotation TO/CO/JA)',
    'MA_BAG_BIO_I': 'Maraîchage plein champ (bagasse, BIO, irrigué)',
    'MA_BAG_BIO_NI': 'Maraîchage plein champ (bagasse, BIO, non irrigué)',
    'MA_BAG_VEG_I': 'Maraîchage plein champ (bagasse, VEG, irrigué)',
    'MA_BAG_VEG_NI': 'Maraîchage plein champ (bagasse, VEG, non irrigué)',
    'MA_BAG_FER_I': 'Maraîchage plein champ (bagasse, FER, irrigué)',
    'MA_BAG_FER_NI': 'Maraîchage plein champ (bagasse, FER, non irrigué)',
    'MA_BAG_NON_I': 'Maraîchage plein champ (bagasse, NON, irrigué)',
    'MA_BAG_NON_NI': 'Maraîchage plein champ (bagasse, NON, non irrigué)',
    'MA_BRF_BIO_I': 'Maraîchage plein champ (BRF, BIO, irrigué)',
    'MA_BRF_BIO_NI': 'Maraîchage plein champ (BRF, BIO, non irrigué)',
    'MA_BRF_VEG_I': 'Maraîchage plein champ (BRF, VEG, irrigué)',
    'MA_BRF_VEG_NI': 'Maraîchage plein champ (BRF, VEG, non irrigué)',
    'MA_BRF_FER_I': 'Maraîchage plein champ (BRF, FER, irrigué)',
    'MA_BRF_FER_NI': 'Maraîchage plein champ (BRF, FER, non irrigué)',
    'MA_BRF_NON_I': 'Maraîchage plein champ (BRF, NON, irrigué)',
    'MA_BRF_NON_NI': 'Maraîchage plein champ (BRF, NON, non irrigué)',
    'MA_PAI_BIO_I': 'Maraîchage plein champ (paille, BIO, irrigué)',
    'MA_PAI_BIO_NI': 'Maraîchage plein champ (paille, BIO, non irrigué)',
    'MA_PAI_VEG_I': 'Maraîchage plein champ (paille, VEG, irrigué)',
    'MA_PAI_VEG_NI': 'Maraîchage plein champ (paille, VEG, non irrigué)',
    'MA_PAI_FER_I': 'Maraîchage plein champ (paille, FER, irrigué)',
    'MA_PAI_FER_NI': 'Maraîchage plein champ (paille, FER, non irrigué)',
    'MA_PAI_NON_I': 'Maraîchage plein champ (paille, NON, irrigué)',
    'MA_PAI_NON_NI': 'Maraîchage plein champ (paille, NON, non irrigué)',
}


def label_for(code: str) -> str:
    """Explicit crop name for a CULT_2017 code, or the code itself if unmapped."""
    return CROP_LABELS.get(code, code)
